---
config_path: /etc/ansible-role-docker-compose
traefik_network: traefik
docker_timeout: 7200
docker_package_timeout: "{{ docker_timeout }}"
docker_registry: docker-registry.balmerfamilyfarm.com
registry_protocol: https
registry_server: docker-registry.balmerfamilyfarm.com
registry_username: "{{ lookup('community.general.onepassword', 'docker-registry.balmerfamilyfarm.com - chrisbalmer', field='username', vault='homelab', username=op_email, subdomain=op_domain, secret_key=op_key, master_password=op_password) }}"
registry_password: "{{ lookup('community.general.onepassword', 'docker-registry.balmerfamilyfarm.com - chrisbalmer', field='password', vault='homelab', username=op_email, subdomain=op_domain, secret_key=op_key, master_password=op_password) }}"
nfs_server: 172.21.129.36
firewall_ports:
  - 8443/tcp